version : '3.8'

services:
  customer-db:
    build: customer_db/.
    ports:
      - '30001:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-db:
    build: stations_db/.
    ports:
      - '30002:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-1-db:
    build: station_1_db/.
    ports:
      - '30011:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-2-db:
    build: station_2_db/.
    ports:
      - '30012:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-3-db:
    build: station_3_db/.
    ports:
      - '30013:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  queue:
    image: rabbitmq:alpine
    ports:
      - '30003:5672'
      - '30083:15672'
